### ISSUE TITLE
Word count stops tracking after a first project cost has been added

### ISSUE THREAD

**Issue by stuartmccoll** [heritagefund/funding-frontend#101]
When adding project costs, the GOV.UK word count component works as expected for the first cost being added. After adding the initial cost and entering a second, the word count component no longer works as expected and remains static with 'You have 50 words remaining'. The component stays in this state for each additional cost being added.

I suspect that this is also happening on similar pages (volunteers, etc).

**Comment by PushBackNeil** [comment]
@stuartmccoll @gidsg @paulmsmith Its an issue with turbo links, I have pushed a fix for this.

**Comment by stuartmccoll** [comment]
Fixed in #108
