### ISSUE TITLE
display error if Direct Upload XHR request returns non 2xx response code

### ISSUE THREAD

**Issue by gidsg** [heritagefund/funding-frontend#124]
# Steps to reproduce
* Download this file, unzip it 
[payload.json.zip](https://github.com/heritagefund/funding-frontend/files/4053116/payload.json.zip)
* Upload the .json file on one of the file upload pages
# Actual Results
Silently fails 
<img width="982" alt="Screenshot 2020-01-13 at 09 52 20" src="https://user-images.githubusercontent.com/1764158/72249178-ba2a9f00-35f0-11ea-9403-376d0d24b9da.png">
# Expected Results
We should detect this state and display a user facing error message

**Comment by gidsg** [comment]
@stuartmccoll I guess this forms part if we are doing a wider refactor to standardise file upload JS.

**Comment by gidsg** [comment]
@stuartmccoll do you know if this is still an issue?

**Comment by stuartmccoll** [comment]
I didn't refactor any of the things that Neil had done as part of the AJAX refactoring - was going to tackle that separately. If Neil's work didn't address this (I don't think it did), then I imagine it'll definitely still be a thing.
