### ISSUE TITLE
IE10 Currency Input (Visual bug)

### ISSUE THREAD

**Issue by paulmsmith** [heritagefund/funding-frontend#255]
![image](https://user-images.githubusercontent.com/57055/73642060-e2924000-4668-11ea-8cda-ddbd1632c0b0.png)

Easily fixable but was not a priority for beta deadline

**Comment by stuartmccoll** [comment]
@paulmsmith You made a change a while ago to use a differently-styled currency input, so I'll close this off as a result. We can open a separate issue if we find that there are compatibility issues with the updated input.
