### ISSUE TITLE
Improve form validation to combine Active Record and strong parameters validations

### ISSUE THREAD

**Issue by stuartmccoll** [heritagefund/funding-frontend#40]
The validation checks used against forms within the service could be made more robust by combining the [validation checks provided by Active Record](https://guides.rubyonrails.org/active_record_validations.html) and by the use of [strong parameters](https://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html).

We've struggled to get these to work in conjunction when a user has submitted an empty form (such as not selecting a radio button), where the strong parameters validation checks then fail because the model object has not been sent through in order to fulfil the `.require()` check. It seems like it _should_ be possible to get both checks to work together, but this will require some time invested into exploring this further.

**Comment by stuartmccoll** [comment]
`params.fetch(:param_name, <default>)` might be the answer here (see the [Rails documentation](https://guides.rubyonrails.org/action_controller_overview.html#more-examples)).

**Comment by naps62** [comment]
@stuartmccoll could you point to an example in the code where this issue is happening? I can't understand it 100% from the description, and I see strong params being used in a lot of places. I'd be interested to see this, because it sounds like something that should just work, if used properly

**Comment by stuartmccoll** [comment]
Hi @naps62. This one is interesting and possibly not well-explained in the issue. I think that the earliest place in the application journey it occurs, or at least a good example of it, would be in [this method](url).

The corresponding view contains a form with a dozen radio buttons. The form is using the `organisation` object. If no radio button is selected, then the payload which comes through to the controller doesn't contain an `organisation` key. Now, if our strong parameters method (in this case `organisation_params`) only contained `params.require(:organisation).permit(:org_type)`, then we end up hitting an `ActionController::ParameterMissing (param is missing or the value is empty: organisation)` error.

To bypass this error, we're doing a check to see if `params` contains an `organisation` key - if it doesn't, then we merge in an empty `organisation` key which contains `{ org_type: '' }` as it's value.

This almost certainly doesn't feel like the right way to do this. Perhaps we should be handling the `ActionController::ParameterMissing error, or investigating whether `params.fetch()` as mentioned above could be used. It feels like there's a best practice in this area that we've not found.

**Comment by naps62** [comment]
@stuartmccoll Ah, got it. That's actually straightforward to solve then

instead of `params.require(:organisation).permit(...)`, you can simply use `params.fetch(:organization, {}).permit(...)`

As documented here: https://guides.rubyonrails.org/action_controller_overview.html#more-examples

**Comment by naps62** [comment]
another alternative would be to have a hidden_field for `org_type` in the form, which would force the inclusion of the `{org_type: ''}` that you mentioned, ensuring the organisation object exists
