### ISSUE TITLE
Adding costs only accepts whole numbers (integers)

### ISSUE THREAD

**Issue by paulmsmith** [heritagefund/funding-frontend#483]
**Describe the bug**
Users get an error message if they enter a cost that is not an integer, for example 500.50

**To reproduce**
Steps to reproduce the behaviour:
1. Go to add project costs
2. Add a cost of 500.50
3. See error

![image](https://user-images.githubusercontent.com/57055/100459767-eb537700-30bd-11eb-91cd-89188b275ebd.png)

Error message for this probably also be more friendly if we don't want decimal numbers. 

**Expected behaviour**
Expect to be able to add decimal numbers

**Comment by stuartmccoll** [comment]
@paulmsmith Going to close this for now, as this was a decision taken early on - to only allow whole numbers (the current form rounds non-whole numbers) - rather than a bug. I believe there's a card on the backlog to re-consider this decision.
