### ISSUE TITLE
Fix GOV.UK JavaScript word count implementation

### ISSUE THREAD

**Issue by stuartmccoll** [heritagefund/funding-frontend#59]
There are a few `TODO` comments in some of the project view files to fix the implementation of the GOV.UK character/word count components.

I've tried dropping the sample component from the GOV.UK Design System straight onto a page without anything else on it and this doesn't work as intended - which makes me think that there's something else going on with the JavaScript being enabled.

**Comment by PushBackNeil** [comment]
I have found the issue, we are initialising gov uk components before the page has finished loading, and it uses the data-module tag to get a count of components to initialise.  I have a fix for it. Will push up a branch for review.

**Comment by stuartmccoll** [comment]
Fixed in #81.
