### ISSUE TITLE
display flash[:notice] and flash[:alert] messages on Devise pages

### ISSUE THREAD

**Issue by gidsg** [heritagefund/funding-frontend#62]
Currently we are not displaying notifications on the sign-in/sign-up pages. We need to include `flash[:notice]` and `flash[:alert]` in these templates so these are visible.
CC @paulmsmith

**Comment by gidsg** [comment]
I think this is causing this issue on a subsequent page, where the notice is being retained and displayed erroneously here. CC @stuartmccoll 
<img width="584" alt="Screenshot 2020-01-03 at 10 45 29" src="https://user-images.githubusercontent.com/1764158/71719457-521cd180-2e16-11ea-9717-8d83550d0748.png">

**Comment by stuartmccoll** [comment]
I've raised #68 to fix the sign-in message being displayed.

**Comment by paulmsmith** [comment]
Is this something @PushBackNeil can look at today once my branch has been merged in?

**Comment by gidsg** [comment]
I think @PushBackNeil could pick this up. We should use one of the approaches here to restrict it to Devise so it does not affect other pages: https://github.com/plataformatec/devise/wiki/How-To:-Create-custom-layouts
