### ISSUE TITLE
Refactor postcode/address lookup functionality

### ISSUE THREAD

**Issue by stuartmccoll** [heritagefund/funding-frontend#72]
Both the organisation and project sections of the service journey require the ability to lookup an address by postcode and to use the returned address to pre-fill form input values. At the moment, the code to do this is completely duplicated between the organisation and project controllers and views. We should refactor this to abstract it into a single place to make it easier to maintain.

**Comment by gidsg** [comment]
Maybe the simplest server-side way, is to use a shared route and set a query parameter to identify the organisation or project in question?
