### ISSUE TITLE
Use custom FormBuilder elements where applicable over partials

### ISSUE THREAD

**Issue by stuartmccoll** [heritagefund/funding-frontend#97]
I think we could express these kind of custom fields more consisely using custom form builder elements i.e. https://api.rubyonrails.org/v6.0/classes/ActionView/Helpers/FormBuilder.html but happy to raise an issue and look at this post launch

_Originally posted by @gidsg in https://github.com/heritagefund/funding-frontend/pull/93_

**Comment by gidsg** [comment]
@stuartmccoll should we close or re-purpose this now we are using the components thing? Does that have the same functionality for generating IDs and stuff?
